<a href="https://colab.research.google.com/github/krueg-lars-web/DataSciene/blob/main/colab/exercise_01/intro-to-python_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Tasks

Acknowledgements: [Florian Lemmerich](http://lemmerich.net/florian/), for the original version of this Notebook.

## Basic Python

If you are not sure about your Python skills, check the "Python Tutorial" before you start working on these exercises.

### Use Python as a calculator to compute 256²

In [1]:
256**2

65536

### Create a list that contains the 4 strings "alpha", "beta", "gamma", and "delta". Add "epsilon" to the end of this list

In [3]:
a = ["alpha","beta","gamma","delta"]
a.append("epsilon")
print(a)

['alpha', 'beta', 'gamma', 'delta', 'epsilon']

### Create a sublist with the first three elements of this list

In [5]:
a[:3]

['alpha', 'beta', 'gamma']

### Write a Python program to construct the following pattern using for loops

```raw
*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*
```

In [45]:
for n in range(1,6,1):
  x = ""
  for c in range (n):
    x = x + "* "
  print(x)
for d in range (0,4,1):
  x = ""
  for f in range(4-d):
      x = x + "* "
  print(x)

*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*

### Write a function that takes 3 input parameters and returns the product of these values

In [39]:
def function1(x, y, z):
  a = x*y*z
  return a

function1(2, 3, 6)

36

### Write a Python function that takes an int as a parameter and checks if the number is prime or not.

In [49]:
def prime(i):
  for n in range (2,i):
    if i % n == 0:
      return False
  return True


prime(7)

True

### Use your function to create a list that contains all primes from 2 to 100

In [52]:
primelist = []
for n in range(2, 101, 1):
  if prime(n) == True:
    primelist.append(n)
primelist

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

### Write a function that simulates dice rolls (6-sided dices)
- Write a function that has the number of dice rolls as the input parameter
- The output is a map with the counts how often each result of a roll (1-6) occurred
- You can use the randomint() function from the random package

In [53]:
# load the random package
import random

In [74]:
def Würfeln(w):
  Ergebnis = {}
  for k in range(1,7,1):
    Ergebnis[k]=0
  for n in range(w):
        a = random.randint(1,6)
        Ergebnis[a] = Ergebnis[a] + 1
  return Ergebnis


Würfeln(100)

{1: 19, 2: 16, 3: 13, 4: 19, 5: 15, 6: 18}

### Combine two dictionaries by adding values for common keys.
d1 = {'a': 100, 'b': 200, 'c':300}

d2 = {'a': 300, 'b': 200, 'd':400}

Sample output: {'a': 400, 'b': 400, 'd': 400, 'c': 300}

In [81]:
d1 = {'a': 100, 'b': 200, 'c':300}

d2 = {'a': 300, 'b': 200, 'd':400}

d = {}

list(d1.keys())

for h in list(d1.keys()) + list(d2.keys()):
  if h not in d:
    d[h] = d1.get(h,0) + d2.get(h,0)
d

{'a': 400, 'b': 400, 'c': 300, 'd': 400}

### Create a list of lists. Then, write a list comprehension that creates a list with the lengths of each (sub)list in the primary list

In [100]:
k= [[1,4,5,6,7,9],[22,24,26,21,21],[34, 37, 38, 39]]
j = [len(k[0]),len(k[1]),len(k[2])]
i = []


for t in range(len(k)):
  i.append(len(k[t]))


g= [len(h) for h in k]

print(j, i, g)

[6, 5, 4] [6, 5, 4] [6, 5, 4]

### Exceptions

Write your own function *my_division* that gets two variables a and b and returns a divided by b. Catch the ZeroDivisionError that occurs if b equals 0 and return 1 in this case.

How could the same behavior be achieved without catching an exception?

In [1]:
def my_division(a,b):
  if b == 0:
    c = 1
  else:
    c = a/b
  return c

my_division(7,0)

1

## Numpy

In this set of tasks, you will have to work with [numpy](https://numpy.org/), the fundamental package for scientific computing with Python.
Make sure to execute the cell below to import the package, we will usually use the abbreviation np for numpy to obtain shorter code.

In [4]:
import numpy as np

### Create a numpy array with 20 rows and 10 columns, where all values are set to zero

In [6]:
np.zeros((20,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Create an array with the same shape containing all natural numbers 0-199

In [8]:
np.arange(0,200).reshape((10,20))

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
        193, 194, 195, 196, 197, 198, 199]])

### Create a 4-dimensional array with exactly 16 elements and set all values to a random integer smaller than 5

In [11]:
array = np.random.randint(0,5,(2,2,2,2))
array

array([[[[3, 1],
         [2, 3]],

        [[0, 0],
         [4, 4]]],


       [[[2, 2],
         [3, 3]],

        [[0, 4],
         [2, 4]]]])

### What is the mean of all values contained in this array?

In [12]:
np.mean(array)

np.float64(2.3125)

### Select a sub-array containing exactly two elements of that array!

In [20]:
array[1,1,1]

array([2, 4])

### Given a numpy array, return a new numpy array that contains only the elements that are greater than 100

In [35]:
a=np.random.randint(0,667,69)
b = a[a>100]
#for k in range(len(a)):
  #if a[k] >100:
   # b.append(a[k])


print(a,b)

[465 402 191 547 623 550 201 553 579 413 645 630 266 649 496 273  27  16
 503 632 119 243 415 303 226 393 394 541  34 642 111  34 628 495 487 370
 350 566  51 148 229  97 576 454 480 536 538 156 262 341 643 142 207 388
 192  47 338 129  49 401 185 503  26 498 246 356 175 554 290] [465 402 191 547 623 550 201 553 579 413 645 630 266 649 496 273 503 632
 119 243 415 303 226 393 394 541 642 111 628 495 487 370 350 566 148 229
 576 454 480 536 538 156 262 341 643 142 207 388 192 338 129 401 185 503
 498 246 356 175 554 290]

## Pandas

> **pandas** is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.<br/>[(source)](https://pandas.pydata.org/)

We will do a couple of simple things here. For more material see:
* [10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html) (this is probably more than ten minutes ;))
* [Pandas tutorial by Kaggle](https://www.kaggle.com/learn/pandas)

In [36]:
import pandas as pd

### Download and read the Titanic dataset using pandas.

In [37]:
import kagglehub
path = kagglehub.dataset_download("yasserh/titanic-dataset/versions/1", path="Titanic-Dataset.csv")
print("Path to dataset files:", path)

Using Colab cache for faster access to the 'titanic-dataset' dataset.
Path to dataset files: /kaggle/input/titanic-dataset/Titanic-Dataset.csv

* see [`read_csv` documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) for an example
* make sure the `index` is set to the `PassengerId`

In [40]:
titanic=pd.read_csv(path,index_col="PassengerId")
titanic

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Display the first/last five rows of the dataset you loaded

In [42]:
titanic[:5]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Use the `describe` method to look at the features in the dataset.

In [44]:
titanic.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

### Select the `Survived` variable and store it in `y`

In [47]:
y=titanic['Survived']
y

PassengerId
1      0
2      1
3      1
4      1
5      0
      ..
887    0
888    1
889    0
890    1
891    0
Name: Survived, Length: 891, dtype: int64

### Select all variables of type `numeric` except `Survived` and store it in `X`

*Hint*: Use panda's `select_dtypes`.

In [55]:
x = titanic.select_dtypes("number").drop(columns='Survived')
x

             Pclass   Age  SibSp  Parch     Fare
PassengerId
1                 3  22.0      1      0   7.2500
2                 1  38.0      1      0  71.2833
3                 3  26.0      0      0   7.9250
4                 1  35.0      1      0  53.1000
5                 3  35.0      0      0   8.0500
...             ...   ...    ...    ...      ...
887               2  27.0      0      0  13.0000
888               1  19.0      0      0  30.0000
889               3   NaN      1      2  23.4500
890               1  26.0      0      0  30.0000
891               3  32.0      0      0   7.7500

[891 rows x 5 columns]

### Calculate the number of NAs (not defined values) for each variables in `X`

In [70]:
a = {}
for k in x.columns:
  a[k] = pd.isna(x[k]).sum()
#print(a)

a, max(a,key=a.get)

({'Pclass': np.int64(0),
  'Age': np.int64(177),
  'SibSp': np.int64(0),
  'Parch': np.int64(0),
  'Fare': np.int64(0)},
 'Age')

Also, which variable has the most NAs?

### Calculate the mean, standard deviation, size and the number of defined values for the `Age` for each `Pclass`

*Hint*: Use `groupby`

In [73]:
x.groupby("Pclass")["Age"].agg(["mean", "std", "size", "count"])

             mean        std  size  count
Pclass
1       38.233441  14.802856   216    186
2       29.877630  14.001077   184    173
3       25.140620  12.495398   491    355

## Bonus: Plotting

The `matplotlib` library is one of the main libraries for visualziations in Python. `seaborn` builds on `matplotlib` and provides easier access to common plotting scenarios.

### Matplotlib

1) Follow the [pyplot tutorial](https://matplotlib.org/stable/tutorials/introductory/pyplot.html) including *"Plotting with categorical variables"*.
2) Apply at least one of the plots to the titanic dataset from above.

*Note*: It makes sense to eventually learn the "explicit" `matplotlib` API (also see [here](https://matplotlib.org/stable/users/explain/figure/api_interfaces.html#api-interfaces) and [here](https://matplotlib.org/stable/tutorials/lifecycle.html)).

## Bonus: Model learning

* Fit a model that predicts whether a passenger `Survived` using [Scikit-Learn](https://scikit-learn.org/stable/). See the [supervised machine learning tutorial](https://scikit-learn.org/1.4/tutorial/statistical_inference/supervised_learning.html) for reference.
* Evaluate the performance of your model.
* Try to optimize your model.